enum AIType { PERCEPTRON_QL, SINGLE_QL, MEMORY_QL, MULTI_QL,
			  BASIC_BT }

enum QLFeature { POS_X_DIFF, POS_Y_DIFF, ENEMY_DIST, SELF_LIFE,
				 ENEMY_LIFE, ENEMY_ATTACKING, ENEMY_DIR_X,
				 ENEMY_DIR_Y, BIAS, FEATURES_SIZE }

enum BTFeature { POS_X_DIFF, POS_Y_DIFF, SELF_X_DIR, SELF_Y_DIR,
				 SELF_LIFE, SELF_MAXLIFE, SELF_DAMAGE, SELF_DEFENSE,
				 ENEMY_X_DIR, ENEMY_Y_DIR, ENEMY_LIFE, ENEMY_MAXLIFE,
				 ENEMY_DAMAGE, ENEMY_DEFENSE, ENEMY_DIST,
				 ENEMY_ATTACKING }